def get_xception():
    pass